# Generated by Django 2.0.7 on 2018-07-23 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('L', '大'), ('M', '中'), ('S', '小')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
