# Generated by Django 2.0.7 on 2018-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=255),
            preserve_default=False,
        ),
    ]
